package tui

import (
	"strconv"
	"strings"
	"time"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
	"github.com/mattn/go-runewidth"

	"github.com/0xReLogic/SENTINEL/checker"
	"github.com/charmbracelet/bubbles/help"
	"github.com/charmbracelet/bubbles/key"
	"github.com/charmbracelet/bubbles/viewport"
)

// TableModel defines a state for the table widget.
type TableModel struct {
	KeyMap 		KeyMap
	Help   		help.Model

	cols   		[]Column
	rows   		[]Row
	cursor 		int
	focus  		bool
	styles 		Styles
	height		int 
	selected 	int
	width		int
	viewport 	viewport.Model
	start    	int
	end      	int
}

// Row represents one line in the table.
type Row []string

// Column defines the table structure.
type Column struct {
	Title string
	Width int
}
// Styles contains style definitions for this list component. By default, these
// values are generated by DefaultStyles.
type Styles struct {
	Header   lipgloss.Style
	Cell     lipgloss.Style
	Selected lipgloss.Style
}

// DefaultStyles returns a set of default style definitions for this table.
func TableDefaultStyles() Styles {
	return Styles{
		Selected: lipgloss.NewStyle(),
		Header:   lipgloss.NewStyle().Bold(true).Padding(0, 1),
		Cell:     lipgloss.NewStyle().Padding(0, 1),
	}
}

// SetStyles sets the table styles.
func (m *TableModel) SetStyles(s Styles) {
	m.styles = s
	m.UpdateViewport()
}

// Option is used to set options in New. For example:
//
//	table := New(TableWithColumns([]Column{{Title: "ID", Width: 10}}))
type Option func(*TableModel)

// New creates a new model for the table widget.
func NewTableModel(opts ...Option) TableModel {
	m := TableModel{
		cursor:   0,
		viewport: viewport.New(0, 20), //nolint:mnd

		KeyMap: DefaultKeyMap(),
		Help:   help.New(),
		styles: TableDefaultStyles(),
	}

	for _, opt := range opts {
		opt(&m)
	}

	m.UpdateViewport()

	return m
}

func ( m TableModel ) CreateTable(  ) ( TableModel ) {
	
	t := NewTableModel(
		TableWithFocused( true ),
		TableWithHeight( m.height - 7 ),
	)
	
	width := m.width - 10 
	serviceWidth := ( ( width / 8 ) * 3 ) + ( width % 8 )
	statusWidth := ( width / 8 ) * 3
	responseWidth := width / 8

	columns := []Column{
		{ Title: "Service", Width: serviceWidth },
		{ Title: "Status", Width: statusWidth },
		{ Title: "Response", Width: responseWidth },
		{ Title: "Time", Width: responseWidth },
	}
	
	t.SetColumns( columns )
	s := TableDefaultStyles()
	s.Header = s.Header.
		BorderStyle( lipgloss.ThickBorder() ).
		BorderForeground( lipgloss.Color( "#ffffff" ) ).
		BorderBottom( true )

	t.SetStyles( s )


	return t
}

func ( m TableModel ) UpdateRows( filterText string, status []checker.ServiceStatus ) TableModel {

	rows := []Row{}
	
	for _, serviceStatus := range status {	
		if filterText != "" && !strings.Contains( strings.ToLower( serviceStatus.Name ), strings.ToLower( filterText ) ) {
			continue
		}
		isUp := lipgloss.NewStyle().Foreground( lipgloss.Color( "#f71111" ) ).Render( "●" ) + " DOWN"
		if serviceStatus.IsUp {
			isUp = lipgloss.NewStyle().Foreground( lipgloss.Color( "#28fc02" ) ).Render( "●" ) + " UP"
		}

		responseCode := strconv.Itoa( serviceStatus.StatusCode )
		if serviceStatus.Error != nil {
			responseCode = "ERROR"
		}
		responseTime := serviceStatus.ResponseTime.Truncate( time.Millisecond ).String()
		rows = append( rows, Row{ serviceStatus.Name, isUp , responseCode , responseTime } )
	}
	
	m.SetRows( rows )

	return m 
}

func( m TableModel ) handleResize( height, width int ) TableModel {
	
	m.height = height
	m.width = width
	return m
}


// TableWithColumns sets the table columns (headers).
func TableWithColumns(cols []Column) Option {
	return func(m *TableModel) {
		m.cols = cols
	}
}

// TableWithRows sets the table rows (data).
func TableWithRows(rows []Row) Option {
	return func(m *TableModel) {
		m.rows = rows
	}
}

// TableWithHeight sets the height of the table.
func TableWithHeight(h int) Option {
	return func(m *TableModel) {
		m.viewport.Height = h - lipgloss.Height(m.headersView())
	}
}

// TableWithWidth sets the width of the table.
func TableWithWidth(w int) Option {
	return func(m *TableModel) {
		m.viewport.Width = w
	}
}

// TableWithFocused sets the focus state of the table.
func TableWithFocused(f bool) Option {
	return func(m *TableModel) {
		m.focus = f
	}
}

// TableWithStyles sets the table styles.
func TableWithStyles(s Styles) Option {
	return func(m *TableModel) {
		m.styles = s
	}
}

// TableWithKeyMap sets the key map.
func TableWithKeyMap(km KeyMap) Option {
	return func(m *TableModel) {
		m.KeyMap = km
	}
}

// Update is the Bubble Tea update loop.
func (m TableModel) Update(msg tea.Msg) (TableModel, tea.Cmd) {
	if !m.focus {
		return m, nil
	}

	switch msg := msg.(type) {
	case tea.KeyMsg:
		switch {
		case key.Matches(msg, m.KeyMap.LineUp):
			m.MoveUp(1)
		case key.Matches(msg, m.KeyMap.LineDown):
			m.MoveDown(1)
		case key.Matches(msg, m.KeyMap.PageUp):
			m.MoveUp(m.viewport.Height)
		case key.Matches(msg, m.KeyMap.PageDown):
			m.MoveDown(m.viewport.Height)
		case key.Matches(msg, m.KeyMap.HalfPageUp):
			m.MoveUp(m.viewport.Height / 2) //nolint:mnd
		case key.Matches(msg, m.KeyMap.HalfPageDown):
			m.MoveDown(m.viewport.Height / 2) //nolint:mnd
		case key.Matches(msg, m.KeyMap.GotoTop):
			m.GotoTop()
		case key.Matches(msg, m.KeyMap.GotoBottom):
			m.GotoBottom()
		case key.Matches( msg, m.KeyMap.ViewService ):
			return m, ChangeView( m.SelectedRow()[0] )
		}
	}

	return m, nil
}

// Focused returns the focus state of the table.
func (m TableModel) Focused() bool {
	return m.focus
}

// Focus focuses the table, allowing the user to move around the rows and
// interact.
func (m *TableModel) Focus() {
	m.focus = true
	m.UpdateViewport()
}

// Blur blurs the table, preventing selection or movement.
func (m *TableModel) Blur() {
	m.focus = false
	m.UpdateViewport()
}

// View renders the component.
func (m TableModel) View() string {
	return m.headersView() + "\n" + m.viewport.View()
}

// HelpView is a helper method for rendering the help menu from the keymap.
// Note that this view is not rendered by default and you must call it
// manually in your application, where applicable.
func (m TableModel) HelpView() string {
	return m.Help.View(m.KeyMap)
}

// UpdateViewport updates the list content based on the previously defined
// columns and rows.
func (m *TableModel) UpdateViewport() {
	renderedRows := make([]string, 0, len(m.rows))

	// Render only rows from: m.cursor-m.viewport.Height to: m.cursor+m.viewport.Height
	// Constant runtime, independent of number of rows in a table.
	// Limits the number of renderedRows to a maximum of 2*m.viewport.Height
	if m.cursor >= 0 {
		m.start = clamp(m.cursor-m.viewport.Height, 0, m.cursor)
	} else {
		m.start = 0
	}
	m.end = clamp(m.cursor+m.viewport.Height, m.cursor, len(m.rows))
	for i := m.start; i < m.end; i++ {
		renderedRows = append(renderedRows, m.renderRow(i))
	}

	m.viewport.SetContent(
		lipgloss.JoinVertical(lipgloss.Left, renderedRows...),
	)
}

// SelectedRow returns the selected row.
// You can cast it to your own implementation.
func (m TableModel) SelectedRow() Row {
	if m.cursor < 0 || m.cursor >= len(m.rows) {
		return nil
	}

	return m.rows[m.cursor]
}

// Rows returns the current rows.
func (m TableModel) Rows() []Row {
	return m.rows
}

// Columns returns the current columns.
func (m TableModel) Columns() []Column {
	return m.cols
}

// SetRows sets a new rows state.
func (m *TableModel) SetRows(r []Row) {
	m.rows = r

	if m.cursor > len(m.rows)-1 {
		m.cursor = len(m.rows) - 1
	}

	m.UpdateViewport()
}

// SetColumns sets a new columns state.
func (m *TableModel) SetColumns(c []Column) {
	m.cols = c
	m.UpdateViewport()
}

// SetWidth sets the width of the viewport of the table.
func (m *TableModel) SetWidth(w int) {
	m.viewport.Width = w
	m.UpdateViewport()
}

// SetHeight sets the height of the viewport of the table.
func (m *TableModel) SetHeight(h int) {
	m.viewport.Height = h - lipgloss.Height(m.headersView())
	m.UpdateViewport()
}

// Height returns the viewport height of the table.
func (m TableModel) Height() int {
	return m.viewport.Height
}

// Width returns the viewport width of the table.
func (m TableModel) Width() int {
	return m.viewport.Width
}

// Cursor returns the index of the selected row.
func (m TableModel) Cursor() int {
	return m.cursor
}

// SetCursor sets the cursor position in the table.
func (m *TableModel) SetCursor(n int) {
	m.cursor = clamp(n, 0, len(m.rows)-1)
	m.UpdateViewport()
}

// MoveUp moves the selection up by any number of rows.
// It can not go above the first row.
func (m *TableModel) MoveUp(n int) {
	m.cursor = clamp(m.cursor-n, 0, len(m.rows)-1)
	switch {
	case m.start == 0:
		m.viewport.SetYOffset(clamp(m.viewport.YOffset, 0, m.cursor))
	case m.start < m.viewport.Height:
		m.viewport.YOffset = (clamp(clamp(m.viewport.YOffset+n, 0, m.cursor), 0, m.viewport.Height))
	case m.viewport.YOffset >= 1:
		m.viewport.YOffset = clamp(m.viewport.YOffset+n, 1, m.viewport.Height)
	}
	m.UpdateViewport()
}

// MoveDown moves the selection down by any number of rows.
// It can not go below the last row.
func (m *TableModel) MoveDown(n int) {
	m.cursor = clamp(m.cursor+n, 0, len(m.rows)-1)
	m.UpdateViewport()

	switch {
	case m.end == len(m.rows) && m.viewport.YOffset > 0:
		m.viewport.SetYOffset(clamp(m.viewport.YOffset-n, 1, m.viewport.Height))
	case m.cursor > (m.end-m.start)/2 && m.viewport.YOffset > 0:
		m.viewport.SetYOffset(clamp(m.viewport.YOffset-n, 1, m.cursor))
	case m.viewport.YOffset > 1:
	case m.cursor > m.viewport.YOffset+m.viewport.Height-1:
		m.viewport.SetYOffset(clamp(m.viewport.YOffset+1, 0, 1))
	}
}

// GotoTop moves the selection to the first row.
func (m *TableModel) GotoTop() {
	m.MoveUp(m.cursor)
}

// GotoBottom moves the selection to the last row.
func (m *TableModel) GotoBottom() {
	m.MoveDown(len(m.rows))
}

// FromValues create the table rows from a simple string. It uses `\n` by
// default for getting all the rows and the given separator for the fields on
// each row.
func (m *TableModel) FromValues(value, separator string) {
	rows := []Row{}
	for _, line := range strings.Split(value, "\n") {
		r := Row{}
		for _, field := range strings.Split(line, separator) {
			r = append(r, field)
		}
		rows = append(rows, r)
	}

	m.SetRows(rows)
}

func (m TableModel) headersView() string {
	s := make([]string, 0, len(m.cols))
	for _, col := range m.cols {
		if col.Width <= 0 {
			continue
		}
		style := lipgloss.NewStyle().Width(col.Width).MaxWidth(col.Width).Inline(true)
		renderedCell := style.Render(runewidth.Truncate(col.Title, col.Width, "…"))
		s = append(s, m.styles.Header.Render(renderedCell))
	}
	return lipgloss.JoinHorizontal(lipgloss.Top, s...)
}

func (m *TableModel) renderRow(r int) string {
	s := make([]string, 0, len(m.cols))
	for i, value := range m.rows[r] {
		if m.cols[i].Width <= 0 {
			continue
		}
		style := lipgloss.NewStyle().Width(m.cols[i].Width).MaxWidth(m.cols[i].Width).Inline(true)
		renderedCell := m.styles.Cell.Render(style.Render(runewidth.Truncate(value, m.cols[i].Width, "…")))
		s = append(s, renderedCell)
	}

	row := lipgloss.JoinHorizontal(lipgloss.Top, s...)

	if r == m.cursor {
		return m.styles.Selected.Render( "▶" + row )
	}

	return row
}

func clamp(v, low, high int) int {
	return min(max(v, low), high)
}
